version: 1.0
app:
  # build id to deploy
  # version: 1.0-SNAPSHOT-20230716015630
  # number of instances
  instances:
    # q: consider availability zones? 

    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 3
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    # q: what's the overall limit?
    max: 6
  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    # q: what's the overall limit?
    # q: do we support fractions?
    cpu: 2
    # memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    # ephemeral disk limit will be set to 1GB  
  # List of environment variables that set for the application
  # Liberty encrypted values are supported only if referenced in server.xml
  env:
    - name: JVM_ARGS # q: make that as a top level 'jvmArguments' property?
      value: "-DenvironmentType=stage"
    - name: MY_ENV
      value: "1"
    - name: tradeDbHost
      #value: "125f9f61-9715-46f9-9399-c8177b21803b.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud"
      value: "ec2-35-153-18-9.compute-1.amazonaws.com"
    - name: tradeDbName
      #value: bludb
      value: TRADEDB
    - name: tradeDbPort
      #value: "30426"
      value: "60005"
    - name: dbUser
      #value: vbd91286
      value: db2inst1
    # - name: dbPass
      # value: "{xor}Oz1tLz4sLChvLTs="
      #value: "{xor}aBwcKx0lDjkGJThsbAYObA=="
      #value: "7CCtBzQfYzg33YQ3"
      # value: "db2passw0rd"
    - name: sslconn
      #value: "true"
      value: "false"
    - name: QueueManager
      value: QM1
    - name: sslciphersuite
      value: "SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      #value: 'TLS_AES_128_GCM_SHA256'
    - name: mqHost
      #value: 'qm1-7ede.qm.us-south.mq.appdomain.cloud' #hostname where MQ container is running
      value: 'ec2-35-153-18-9.compute-1.amazonaws.com'
    - name: mqPort
      #value: "30973"
      value: "1414"
    - name: mqChannel
      #value: "CLOUD.APP.SVRCONN"
      value: "DEV.APP.SVRCONN"
    - name: mqUser
      value: "app"
    # - name: mqPass
      # value: "{xor}Mi4vPiwsKG8tOw=="
      #value: "{aes}ACGv685f2PtN9s2NlsmLyRRJd8dxOSzyWXOl5JWJ/QjQDZ/GgZdyU3KrkHib+vx2QKoCPDHETwBcNs6c3W0UDiyuJiRk6ph/TwOCyxxFJYJm"
      #value: "{xor}DAUyFjoRCSoxEisbGBoTEzBnBzw9azEmLDoAMxgcMRY5BS8GMygWaDwVMWs="
      #value: "SZmIeNVunMtDGELLo8Xcb4nyse_lGCnIfZpYlwI7cJn4"
      # value: "mqpassw0rd"
  # List of variables that can be referenced in server.xml
  # Liberty encrypted values are supported
  variables:
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: discoveryEndpoint
      value: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eksr97OJU/.well-known/openid-configuration"
    - name: clientId
      value: 7rgjkvbjl487r2i1bvialvj2f4
    - name: clientSecret
      value: "{aes}AIUxkkmTE73hJrAj3oN5OMYQnC9j3NWNJNTXXAchJ97qyrr7MHYMmn1NEtxgHXFqmYp8VNEAYhB5hJS8voLsRYyfA/7GpDdznGs/DtYEqzlw"
  # cloudwatch for metrics

  # version:
  version: ""
  # version: "7871cfbe-c7d3-4711-a91c-56812a670273"
# probes
# dynamic scaling
# scaling to 0
