version: 1.0
app:
  # build id to deploy
  # version: 1.0-SNAPSHOT-20230716015630
  # number of instances
  instances:
    # q: consider availability zones? 

    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    # q: what's the overall limit?
    max: 1
  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    # q: what's the overall limit?
    # q: do we support fractions?
    cpu: 2
    # memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    # ephemeral disk limit will be set to 1GB  
  # List of environment variables that set for the application
  # Liberty encrypted values are supported only if referenced in server.xml
  services:
    - crn: "crn:v1:bluemix:public:mqcloud:us-east:a/67165156f10340b4a16f9a90b4d63e27:33f489f6-eae9-4d9e-9a39-db942426e00d::"
  env:
    - name: WLP_LOGGING_STACK_TRACE_SINGLE_ENTRY
      value: "true"
    - name: tradeDbHost
      value: "bad33e-8bf9-0fbb7e483086.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud"
      #value: "ec2-35-153-18-9.compute-1.amazonaws.com"
    - name: tradeDbName
      value: bludb
      #value: TRADEDB
    - name: tradeDbPort
      value: "32459"
      #value: "60005"
    - name: dbUser
      value: lnl43017
      #value: db2inst1
    - name: dbPass
      value: "{xor}G2cNDxYYCCU9HDI0OggaJQ=="
      #value: "{xor}aBwcKx0lDjkGJThsbAYObA=="
      #value: "7CCtBzQfYzg33YQ3"
      # value: "db2passw0rd"
    - name: sslconn
      value: "true"
      #value: "false"
    - name: mqUser
      value: "app"
  # List of variables that can be referenced in server.xml
  # Liberty encrypted values are supported
  variables:
    - name: MQCredentials
      value: "XhL9JqEIezCDQlIPpn_Hm8wjWo6tT5Y6OWoH6g06QtwV"
  systemProperties:
    - name: com.ibm.mq.cfg.SSL.outboundSNI
      value: HOSTNAME
    #- name: javax.net.debug
    #  value: "ssl,handshake"
  # version:
  version: "a504e221-4041-4c0b-9733-17b0f4fc310e"
  endpoints: public
